// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package main

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

// ===================================
// TransferPayload
// ===================================

func (v *TransferPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "to":
			v.To = string(in.String())
		case "amount":
			v.Amount = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v TransferPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"to":`)
	out.String(v.To)
	out.RawString(`,"amount":`)
	out.Uint64(v.Amount)
	out.RawByte('}')
}

func (v TransferPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

func (v *TransferPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&r)
	return r.Error()
}

// ===================================
// TransferFromPayload
// ===================================

func (v *TransferFromPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "from":
			v.From = string(in.String())
		case "to":
			v.To = string(in.String())
		case "amount":
			v.Amount = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v TransferFromPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"from":`)
	out.String(v.From)
	out.RawString(`,"to":`)
	out.String(v.To)
	out.RawString(`,"amount":`)
	out.Uint64(v.Amount)
	out.RawByte('}')
}

func (v TransferFromPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

func (v *TransferFromPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&r)
	return r.Error()
}

// ===================================
// ApprovePayload
// ===================================

func (v *ApprovePayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "spender":
			v.Spender = string(in.String())
		case "amount":
			v.Amount = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v ApprovePayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"spender":`)
	out.String(v.Spender)
	out.RawString(`,"amount":`)
	out.Uint64(v.Amount)
	out.RawByte('}')
}

func (v ApprovePayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

func (v *ApprovePayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&r)
	return r.Error()
}

// ===================================
// AllowancePayload (for increase/decrease)
// ===================================

func (v *AllowancePayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "spender":
			v.Spender = string(in.String())
		case "amount":
			v.Amount = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v AllowancePayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"spender":`)
	out.String(v.Spender)
	out.RawString(`,"amount":`)
	out.Uint64(v.Amount)
	out.RawByte('}')
}

func (v AllowancePayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

func (v *AllowancePayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&r)
	return r.Error()
}

// ===================================
// GetAllowancePayload
// ===================================

func (v *GetAllowancePayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "owner":
			v.Owner = string(in.String())
		case "spender":
			v.Spender = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v GetAllowancePayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"owner":`)
	out.String(v.Owner)
	out.RawString(`,"spender":`)
	out.String(v.Spender)
	out.RawByte('}')
}

func (v GetAllowancePayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

func (v *GetAllowancePayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&r)
	return r.Error()
}

// ===================================
// BalancePayload
// ===================================

func (v *BalancePayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "account":
			v.Account = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v BalancePayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"account":`)
	out.String(v.Account)
	out.RawByte('}')
}

func (v BalancePayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

func (v *BalancePayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&r)
	return r.Error()
}

// ===================================
// MintPayload
// ===================================

func (v *MintPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			v.Amount = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v MintPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"amount":`)
	out.Uint64(v.Amount)
	out.RawByte('}')
}

func (v MintPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

func (v *MintPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&r)
	return r.Error()
}

// ===================================
// BurnPayload
// ===================================

func (v *BurnPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			v.Amount = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v BurnPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"amount":`)
	out.Uint64(v.Amount)
	out.RawByte('}')
}

func (v BurnPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

func (v *BurnPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&r)
	return r.Error()
}

// ===================================
// ChangeOwnerPayload
// ===================================

func (v *ChangeOwnerPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "newOwner":
			v.NewOwner = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v ChangeOwnerPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"newOwner":`)
	out.String(v.NewOwner)
	out.RawByte('}')
}

func (v ChangeOwnerPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

func (v *ChangeOwnerPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&r)
	return r.Error()
}

// ===================================
// Response Types
// ===================================

// BalanceResponse
func (v BalanceResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"balance":`)
	out.Uint64(v.Balance)
	out.RawByte('}')
}

func (v BalanceResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// SupplyResponse
func (v SupplyResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"totalSupply":`)
	out.Uint64(v.TotalSupply)
	out.RawByte('}')
}

func (v SupplyResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// AllowanceResponse
func (v AllowanceResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"allowance":`)
	out.Uint64(v.Allowance)
	out.RawByte('}')
}

func (v AllowanceResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// OwnerResponse
func (v OwnerResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"owner":`)
	out.String(v.Owner)
	out.RawByte('}')
}

func (v OwnerResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// InfoResponse
func (v InfoResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"name":`)
	out.String(v.Name)
	out.RawString(`,"symbol":`)
	out.String(v.Symbol)
	out.RawString(`,"decimals":`)
	out.Int(v.Decimals)
	out.RawString(`,"maxSupply":`)
	out.Uint64(v.MaxSupply)
	out.RawByte('}')
}

func (v InfoResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// PausedResponse
func (v PausedResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"paused":`)
	out.Bool(v.Paused)
	out.RawByte('}')
}

func (v PausedResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// SuccessResponse
func (v SuccessResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"success":`)
	out.Bool(v.Success)
	out.RawByte('}')
}

func (v SuccessResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// ===================================
// Event Types
// ===================================

// InitEvent
func (v InitEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

func (v InitEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// InitAttributes
func (v InitAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"owner":`)
	out.String(v.Owner)
	out.RawByte('}')
}

// MintEvent
func (v MintEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

func (v MintEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// MintAttributes
func (v MintAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"to":`)
	out.String(v.To)
	out.RawString(`,"amount":`)
	out.Uint64(v.Amount)
	out.RawByte('}')
}

// BurnEvent
func (v BurnEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

func (v BurnEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// BurnAttributes
func (v BurnAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"from":`)
	out.String(v.From)
	out.RawString(`,"amount":`)
	out.Uint64(v.Amount)
	out.RawByte('}')
}

// TransferEvent
func (v TransferEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

func (v TransferEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// TransferAttributes
func (v TransferAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"from":`)
	out.String(v.From)
	out.RawString(`,"to":`)
	out.String(v.To)
	out.RawString(`,"amount":`)
	out.Uint64(v.Amount)
	out.RawByte('}')
}

// ApprovalEvent
func (v ApprovalEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

func (v ApprovalEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// ApprovalAttributes
func (v ApprovalAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"owner":`)
	out.String(v.Owner)
	out.RawString(`,"spender":`)
	out.String(v.Spender)
	out.RawString(`,"amount":`)
	out.Uint64(v.Amount)
	out.RawByte('}')
}

// OwnerChangeEvent
func (v OwnerChangeEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

func (v OwnerChangeEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// OwnerChangeAttributes
func (v OwnerChangeAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"newOwner":`)
	out.String(v.NewOwner)
	out.RawByte('}')
}

// PausedEvent
func (v PausedEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

func (v PausedEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// PausedAttributes
func (v PausedAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"by":`)
	out.String(v.By)
	out.RawByte('}')
}

// UnpausedEvent
func (v UnpausedEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

func (v UnpausedEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// UnpausedAttributes
func (v UnpausedAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"by":`)
	out.String(v.By)
	out.RawByte('}')
}
